### ISSUE TITLE
Ipn sends unicode in response body

### ISSUE THREAD

**Issue by kalekseev** [spookylukey/django-paypal#116] opened 2015-11-04 07:14 UTC
After upgrading to requests 2.8.1 got next error:

```
cannot make memory view because object does not have the buffer interface
```

Related requests issue https://github.com/kennethreitz/requests/issues/2818

The problem appears to be in 
https://github.com/spookylukey/django-paypal/blob/4970094599070c6417cb7937449747a2508eae74/paypal/standard/ipn/models.py#L23

```
b("cmd=_notify-validate&%s" % self.query)
```

`self.query` is unicode as a result request body is unicode too in python 2.7.

**Comment by spookylukey** [comment] 2015-11-04 10:39
Hmm, it turns out `six.b` is a no-op on Python2, while it does `s.encode('latin-1')` on Python 3. The latter behaviour is what I want everywhere.

https://pythonhosted.org/six/#binary-and-text-data

This should be fixed to use `b""` for the string (since we don't need to support Python 2.5) and `self.query.encode('ascii')` I think. Other instances of `six.b()` should also be replaced too.

**Comment by spookylukey** [comment] 2015-12-17 10:05
I can't reproduce this error with requests 2.8.1. An complete traceback would help, with the exact package versions you are using.

**Comment by kalekseev** [comment] 2016-11-30 21:18
Hi @spookylukey, sorry for the late response.
You can reproduce this quite easy with current tests
just set requests==2.8.1 in tox.ini and run `tox -e py27-django18`

**Comment by spookylukey** [comment] 2016-12-14 14:07
Thanks for the info, should have this fixed soon.

**Closed** 2016-12-14 14:27 UTC
Labels: bug
