### ISSUE TITLE
return_url field is no longer hidden

### ISSUE THREAD

**Issue by Gromph** [spookylukey/django-paypal#167] opened 2017-01-30 19:01 UTC
I was trying the master branch to test the fix for issue #166 and noticed that the return_url field is now showing on the web page next to my PayPal checkout button.  The field no longer has type="hidden" set.

**Comment by spookylukey** [comment] 2017-01-31 16:50
Thanks so much for reporting this, it has been fixed now - d8db1f882817e26bb777e2809e428758cb49a8ac

It was caused by a mistake when adding 1.11 support.

**Closed by spookylukey** 2017-01-31 16:50 UTC
