### ISSUE TITLE
Error 500, when PAYPAL_TEST = True

### ISSUE THREAD

**Issue by HigorSilvaRosa** [spookylukey/django-paypal#179] opened 2017-06-26 18:49 UTC
When I try make a sale when PAYPAL_TEST = True, the paypal page return http 500 response,

I dont know if the Paypal servers are with problems, or if the problem is in this module. Im tring since 4 days.

The page "https://www.sandbox.paypal.com/cgi-bin/webscr" returns "Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

This only happens when i'm using the teste mode. When PAYPAL_TEST = False, everything is OK!

**Comment by spookylukey** [comment] 2017-06-26 19:46
If PayPal's servers are is returning 500, it is their error, not django-paypal's.

Dupe of #178

**Closed by spookylukey** 2017-06-26 19:46 UTC
