### ISSUE TITLE
SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE]

### ISSUE THREAD

**Issue by luanfonceca** [spookylukey/django-paypal#145] opened 2016-04-18 06:19 UTC
Hi folks, i am having this issue all day and i cant figure out what should be.

I am running in the localhost the paypal pro, when i submit the payment form i get this error:

```
requests.exceptions.SSLError
SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
```

Thanks in advance for any clues and sorry if this is not directly related with the django-paypal.

o/

**Comment by spookylukey** [comment] 2016-04-18 19:15
It helps if you post the full traceback.

My guess is that your Python/SSL setup is not correct. See http://docs.python-requests.org/en/master/user/advanced/#ca-certificates (warning - this can get complicated)

**Comment by luanfonceca** [comment] 2016-04-18 20:16
Thanks @spookylukey i will read that

o/

**Comment by amureki** [comment] 2016-05-23 18:44
@luanfonceca do you use ngrok on local machine? I've got same error with it (only on local, not on test servers), I guess they have something wrong with SSL certificate.

**Comment by luanfonceca** [comment] 2016-05-23 20:52
@amureki yes i do, i think that should be something with the ssl too

**Comment by kwstewart** [comment] 2016-06-04 21:37
I am having the same issue, but only locally.

**Comment by panosl** [comment] 2016-06-08 17:28
Happening here as well on the local box (osx yosemite, python 2.7.10).

Any ideas?

**Comment by dhontecillas** [comment] 2016-06-08 19:00
I think the problem could be that the PayPal sandbox has no proper support for TLS and the requests library has been updated to not support the downgrade of the SSL protocol to versions that are not safe. For example, to receive the IPN notifications in my server I had setup stunnel ( https://www.stunnel.org/index.html ) , and I had configure it to allow all versions of SSL with this config file:
```
pid=
cert = stunnel.pem
sslVersion = all
foreground = yes
output = stunnel.log
debug=7
options=-NO_SSLv3
options=-NO_SSLv2

[https]
accept=8443
connect=8001
TIMEOUTclose=60
```

The key part there is the options  -NO_SSLv3 .

I guess, that in PayPal Pro the problem is that is our server the one making requests (so, setting up a proxy for incoming connections will not solve the problem), and our library not supporting the protocol downgrade. 

Here is an article about using requests allowing other SSL versions : https://lukasa.co.uk/2013/01/Choosing_SSL_Version_In_Requests/ , but .. that would mean that we have to modify the code.

So, my proposed solution is : 
modify your /etc/hosts file, to resolve the PayPal domain name to a local proxy ip (I don't know if you can use stunnel for this purpose), and configure the proxy to support all SSL protocols.

Does it make sense ?

**Comment by panosl** [comment] 2016-06-08 22:32
@dhontecillas It already worked on my server, the problem was on my development env. On OS X Yosemite, I had to:

```
$ brew update
$ brew install openssl
$ brew link openssl --force 
$ brew install python --with-brewed-openssl    
```

and it works like the server! Apparently the openssl shipped with yosemite (I suppose it applies to everyone on the issue here), was a bit old and didn't handle the issue properly.

A weird thing is that the first post try fails:

```
[09/Jun/2016 01:26:15] "POST /paypal/ HTTP/1.1" 404 1730
[09/Jun/2016 01:26:24] "POST /store/success/ HTTP/1.1" 200 5272
[09/Jun/2016 01:26:32] "POST /paypal/ HTTP/1.0" 200 4
```

but the second one succeeds. So I have two ipn items in my admin, not sure if that's a big issue or not, haven't got that far yet.

**Comment by spookylukey** [comment] 2017-01-28 11:44
It seems this is not an issue with django-paypal, or there is nothing that can be done in this project to fix the error (other than a small documentation note I've added), therefore I'm closing this issue. Please re-open if there is something more that can be done.

**Closed by spookylukey** 2017-01-28 11:44 UTC
