### ISSUE TITLE
Testing IPN Error Notification Code

### ISSUE THREAD

**Issue by blakegibbs** [spookylukey/django-paypal#83] opened 2015-03-09 10:00 UTC
While testing my IPN listener with negative testing, I'm getting errors(Make sure that this value is a maximum of 15 characters) on fields reason_code and pending_reason, changing max_length to 40 resolved my issue.

Also, I'm getting error at paypal\standard\models.py", line 289, in set_flag
    self.flag_info += info
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 116: ordinal not in range(128)

changing this line to self.flag_info += info.decode('utf-8') resolved my issue

**Comment by spookylukey** [comment] 2015-03-09 11:17
I'm not sure what you mean by negative testing. Are these errors when you are receiving actually PayPal HTTP requests on those listeners?

**Comment by blakegibbs** [comment] 2015-03-09 12:26
IPN testing: https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNTesting/
section "Testing Your IPN Error Notification Code"

Errors occurs when paypal posts to my listener using one of those error triggers. Simple transaction works fine.

**Comment by spookylukey** [comment] 2015-06-10 11:04
When trying this negative testing, I first hit a problem with the "charset" not being included. This is a bug in the IPN simulator which I have contact PayPal about.

**Comment by spookylukey** [comment] 2015-06-10 14:39
I've added a workaround for my last issue, but I still can't reproduce the errors you're talking about. The docs talk about setting the `amount` field - but there is no such field! I've tried setting the `mc_gross` field to the specified amounts, but this doesn't do anything - it doesn't trigger the error conditions.

If you can tell me how you are doing this, I may be able to make some progress. Thanks.

**Comment by spookylukey** [comment] 2015-06-12 17:01
OK, I realised that this is not the simulator, but the sandbox. I'll try again at some point.

**Comment by spookylukey** [comment] 2015-06-12 17:35
This should be fixed in master now. I tested with negative and got the same error, due to a field that wasn't long enough.

**Closed by spookylukey** 2015-06-12 17:35 UTC
Labels: needs-info
